### ISSUE TITLE
Fresh-Web

### ISSUE THREAD

**Issue by cynthiahqy** [cynthiahqy/monash-quarto-aea#11]
```yaml
project:
  type: website
  resources:
    - "**/*.pdf"

website:
  title: "fresh-web"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - text: "More"
        menu: 
          - text: Extra
            file: extra.qmd
          - text: CV
            href: assets/CV.pdf
          - about.qmd
  sidebar:
    contents: posts

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
```

**Comment by cynthiahqy** [comment]
_metadata.yml

```yaml
format:
  html:
    author: "Cynthia Huang"
    
description: "shared description"
```
